[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "./node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
formatter = { command = "prettier", args = ["--plugin", "prettier-plugin-astro", "--plugin", "prettier-plugin-tailwindcss", "--parser", "astro"] }

[language-server.tailwindcss-ls]
config = { userLanguages = { rust = "html", "*.rs" = "html", astro = "html", "*.astro" = "html" } }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss-ls"]

[[language]]
name = "astro"
language-servers = ["astro-ls", "tailwindcss-ls"]

