[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "./node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
scope = "source.astro"
injection-regex = "astro"
file-types = ["astro"]
language-servers = ["astro-ls"]
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-astro", "--plugin", "prettier-plugin-tailwindcss", "--parser", "astro"] }

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "babel-ts"] }

[[language]]
name = "javascript"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "babel"] }

[[language]]
name = "tsx"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "babel-ts"] }

[[language]]
name = "jsx"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "babel"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "json"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "css"] }

[[language]]
name = "html"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "html"] }

[[language]]
name = "scss"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "scss"] }

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "markdown"] }

[[language]]
name = "mdx"
scope = "*.mdx"
file-types = ["mdx"]
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "mdx"] }

[[language]]
name = "vue"
formatter = { command = "prettier", args = ["--write", "--plugin", "prettier-plugin-tailwindcss", "--parser", "vue"] }

[language-server.tailwindcss-ls]
config = { userLanguages = { rust = "html", "*.rs" = "html", astro = "html", "*.astro" = "html" } }

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "tailwindcss-ls"]

[[language]]
name = "astro"
language-servers = ["astro-ls", "tailwindcss-ls"]

